# Generated by Django 2.2.6 on 2020-12-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice_Comment',
        ),
    ]
