# Generated by Django 2.2.6 on 2020-12-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_delete_notice_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='From_mark_Comment',
        ),
    ]
