# Generated by Django 2.2.6 on 2020-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_hitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
