# Generated by Django 2.2.6 on 2020-09-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Notice',
        ),
    ]
