# Generated by Django 2.2.6 on 2020-09-12 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20200126_0047'),
        ('board', '0007_auto_20200913_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='FROM_MARK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FROM_MARK_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.FROM_MARK')),
            ],
        ),
    ]
