# Generated by Django 2.2.6 on 2020-09-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200913_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='from_mark_comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='from_mark_comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='FROM_MARK',
        ),
        migrations.DeleteModel(
            name='FROM_MARK_Comment',
        ),
    ]
