# Generated by Django 2.2.6 on 2020-11-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_inquiry_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry_Comment',
        ),
    ]
